version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - ${MYSQL_PORT}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - .data:/var/lib/mysql
    networks:
      - my-network

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-node-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
